using System;

namespace WeTest.U3DAutomation
{
	[Serializable]
	internal enum Cmd
	{
		EXIT,
		GET_VERSION = 100,
		FIND_ELEMENTS,
		FIND_ELEMENT_PATH,
		GET_ELEMENTS_BOUND,
		GET_ELEMENT_WORLD_BOUND,
		GET_UI_INTERACT_STATUS,
		GET_CURRENT_SCENE,
		GET_ELEMENT_TEXT,
		GET_ELEMENT_IMAGE,
		GET_REGISTERED_HANDLERS,
		CALL_REGISTER_HANDLER,
		SET_INPUT_TEXT,
		GET_OBJECT_FIELD,
		HANDLE_TOUCH_EVENTS = 200,
		DUMP_TREE = 300,
		FIND_ELEMENT_BY_POS,
		GET_FPS = 400,
		GET_TRAFFIC_DATA,
		ENTER_RECORD = 500,
		LEAVE_RECORD,
		TOUCH_NOTIFY
	}
}
